// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAitWW8HTs9voFtFzUsx1bslqNzehz-wsc',
    appId: '1:369416843312:web:01ea3d202130246f3c3df5',
    messagingSenderId: '369416843312',
    projectId: 'fir-login-69a22',
    authDomain: 'fir-login-69a22.firebaseapp.com',
    storageBucket: 'fir-login-69a22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuWlElBgSJvstwsRkz-nliDt78ScvCJAY',
    appId: '1:369416843312:android:5e6ae99cf64846f23c3df5',
    messagingSenderId: '369416843312',
    projectId: 'fir-login-69a22',
    storageBucket: 'fir-login-69a22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAduf7zWnAQiruGhv-oJx6W5ymYyDnf_08',
    appId: '1:369416843312:ios:b533e61359ab12163c3df5',
    messagingSenderId: '369416843312',
    projectId: 'fir-login-69a22',
    storageBucket: 'fir-login-69a22.appspot.com',
    iosClientId: '369416843312-86f7hlpjjj6rkcp1s9il805mu1annmh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAduf7zWnAQiruGhv-oJx6W5ymYyDnf_08',
    appId: '1:369416843312:ios:76417d02bd70118c3c3df5',
    messagingSenderId: '369416843312',
    projectId: 'fir-login-69a22',
    storageBucket: 'fir-login-69a22.appspot.com',
    iosClientId: '369416843312-t0optp8m3kvn0bacuj4h485kd3grsqar.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselogin.RunnerTests',
  );
}
